# Generated by Django 4.2.4 on 2023-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Название мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Название мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Название мероприятия'),
        ),
    ]
