# Generated by Django 4.2.4 on 2023-08-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
