# Generated by Django 4.2.4 on 2023-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_date_en_event_date_ru_event_date_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Konsert', 'verbose_name_plural': 'Konsertlar'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_uz',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_uz',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_uz',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=256, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events-photos/%Y/%m/%d', verbose_name='Fotosurat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=256, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Konsert nomi'),
        ),
    ]
