# Generated by Django 4.2.4 on 2023-08-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_options_remove_event_date_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Vaqt'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Vaqt'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Vaqt'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Konsert nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Konsert nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Konsert nomi'),
        ),
    ]
